
package main;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class frmMain extends javax.swing.JFrame {
dbConnection dbConn = new dbConnection();
//Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    public frmMain() {
        initComponents();
        dbConn.doConnect();
        //setBounds(0,0,screenSize.width, screenSize.height);
        setVisible(true);
//        disableAll();
        GetAccess();
//        limitAccess();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    private void GetAccess(){
        try{
            dbConn.SQLQuery = "select * from tblusersecurity where us_name=?";
            dbConn.pstmt = dbConn.conn.prepareStatement(dbConn.SQLQuery);
            dbConn.pstmt.setString(1, dbConn.LoggedInUser);
            dbConn.rs = dbConn.pstmt.executeQuery();
            if(dbConn.rs.next()){
                if (dbConn.rs.getString("us_product").equals("N")){
                    btnProduct.setEnabled(false);
                }

                if (dbConn.rs.getString("us_supplier").equals("N")){
                    btnSupplier.setEnabled(false);
                }

                if (dbConn.rs.getString("us_lpo").equals("N")){
                    btnLPO.setEnabled(false);
                }

                if (dbConn.rs.getString("us_stockadjust").equals("N")){
                    btnStockAdjust.setEnabled(false);
                }

                if (dbConn.rs.getString("us_cashier").equals("N")){
                    btnCashiering.setEnabled(false);
                }

                if (dbConn.rs.getString("us_receipt").equals("N")){
                    btnReceipt.setEnabled(false);
                }

                if (dbConn.rs.getString("us_product").equals("N")){
                    btnProduct.setEnabled(false);
                }

                if (dbConn.rs.getString("us_reports").equals("N")){
                    btnReports.setEnabled(false);
                }

                if (dbConn.rs.getString("us_usercontrol").equals("N")){
                    btnUserControl.setEnabled(false);
                }

                if (dbConn.rs.getString("us_usersecurity").equals("N")){
                    btnUserSecurity.setEnabled(false);
                }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void disableAll(){
        btnCashiering.setEnabled(false);
        btnCustomer.setEnabled(false);
        btnExpenses.setEnabled(false);
        btnLPO.setEnabled(false);
        btnLogOut.setEnabled(false);
        btnLogOut1.setEnabled(false);
        btnProduct.setEnabled(false);
        btnReceipt.setEnabled(false);
        btnReports.setEnabled(false);
        btnStockAdjust.setEnabled(false);
        btnSupplier.setEnabled(false);
        btnUserControl.setEnabled(false);
    }
    private void enableAll(){
        btnCashiering.setEnabled(true);
        btnCustomer.setEnabled(true);
        btnExpenses.setEnabled(true);
        btnLPO.setEnabled(true);
        btnLogOut.setEnabled(true);
        btnLogOut1.setEnabled(true);
        btnProduct.setEnabled(true);
        btnReceipt.setEnabled(true);
        btnReports.setEnabled(true);
        btnStockAdjust.setEnabled(true);
        btnSupplier.setEnabled(true);
        btnUserControl.setEnabled(true);
    }
    private void limitAccess(){
//        if (frmLogin.checkAdmin.equals("Y")){
//            enableAll();
//        }else if (frmLogin.getPosition.equalsIgnoreCase("CASHIER")){
//            btnCashiering.setEnabled(true);
//            btnLogOut.setEnabled(true);
//            btnReceipt.setEnabled(true);
//            btnProduct.setEnabled(true);
//        }else if(frmLogin.getPosition.equalsIgnoreCase("STORE KEEPER")){
//            btnProduct.setEnabled(true);
//            btnLPO.setEnabled(true);
//            btnLogOut.setEnabled(true);
//            btnStockAdjust.setEnabled(true);
//            btnSupplier.setEnabled(true);
//        }else if(frmLogin.getPosition.equalsIgnoreCase("FINANCE")){
//            btnExpenses.setEnabled(true);
//            btnLogOut.setEnabled(true);
//            btnReceipt.setEnabled(true);
//            btnReports.setEnabled(true);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSupplier = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnStockAdjust = new javax.swing.JButton();
        btnLPO = new javax.swing.JButton();
        btnCashiering = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnExpenses = new javax.swing.JButton();
        btnReceipt = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnUserControl = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnLogOut1 = new javax.swing.JButton();
        btnUserSecurity = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 214, 194));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(214, 214, 194));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSupplier.setBackground(new java.awt.Color(255, 255, 255));
        btnSupplier.setForeground(new java.awt.Color(0, 0, 0));
        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/supplierIcon.png"))); // NOI18N
        btnSupplier.setText("SUPPLIER MASTER");
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });
        jPanel2.add(btnSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 240, 100));

        btnProduct.setBackground(new java.awt.Color(255, 255, 255));
        btnProduct.setForeground(new java.awt.Color(0, 0, 0));
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/productIcon.png"))); // NOI18N
        btnProduct.setText("PRODUCT");
        btnProduct.setFocusable(false);
        btnProduct.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
        jPanel2.add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 100));

        btnStockAdjust.setBackground(new java.awt.Color(255, 255, 255));
        btnStockAdjust.setForeground(new java.awt.Color(0, 0, 0));
        btnStockAdjust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/stockAdjustIcon.png"))); // NOI18N
        btnStockAdjust.setText("STOCK ADJUST");
        btnStockAdjust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockAdjustActionPerformed(evt);
            }
        });
        jPanel2.add(btnStockAdjust, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 240, 100));

        btnLPO.setBackground(new java.awt.Color(255, 255, 255));
        btnLPO.setForeground(new java.awt.Color(0, 0, 0));
        btnLPO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/LPOicon.png"))); // NOI18N
        btnLPO.setText("LPO/RECEIVING");
        btnLPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLPOActionPerformed(evt);
            }
        });
        jPanel2.add(btnLPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 240, 100));

        btnCashiering.setBackground(new java.awt.Color(255, 255, 255));
        btnCashiering.setForeground(new java.awt.Color(0, 0, 0));
        btnCashiering.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/cashierIcon.png"))); // NOI18N
        btnCashiering.setText("SALES/CASHIER");
        btnCashiering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashieringActionPerformed(evt);
            }
        });
        jPanel2.add(btnCashiering, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 240, 100));

        btnCustomer.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomer.setForeground(new java.awt.Color(0, 0, 0));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/customerIcon.png"))); // NOI18N
        btnCustomer.setText("CUSTOMER");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        jPanel2.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 240, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 670));

        jPanel4.setBackground(new java.awt.Color(214, 214, 194));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 153)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExpenses.setBackground(new java.awt.Color(255, 255, 255));
        btnExpenses.setForeground(new java.awt.Color(0, 0, 0));
        btnExpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/expenseiCon.png"))); // NOI18N
        btnExpenses.setText("EXPENSES");
        btnExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpensesActionPerformed(evt);
            }
        });
        jPanel4.add(btnExpenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, 80));

        btnReceipt.setBackground(new java.awt.Color(255, 255, 255));
        btnReceipt.setForeground(new java.awt.Color(0, 0, 0));
        btnReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/ReportsIcon2.png"))); // NOI18N
        btnReceipt.setText("RECEIPT RECORDS");
        btnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptActionPerformed(evt);
            }
        });
        jPanel4.add(btnReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 240, 80));

        btnReports.setBackground(new java.awt.Color(255, 255, 255));
        btnReports.setForeground(new java.awt.Color(0, 0, 0));
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/ReportsIcon3.png"))); // NOI18N
        btnReports.setText("REPORTS");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        jPanel4.add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 240, 80));

        btnUserControl.setBackground(new java.awt.Color(255, 255, 255));
        btnUserControl.setForeground(new java.awt.Color(0, 0, 0));
        btnUserControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/useriCon.png"))); // NOI18N
        btnUserControl.setText("USER CONTROL");
        btnUserControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserControlActionPerformed(evt);
            }
        });
        jPanel4.add(btnUserControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 240, 80));

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setForeground(new java.awt.Color(0, 0, 0));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/logoutIcon.png"))); // NOI18N
        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel4.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 240, 80));

        btnLogOut1.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut1.setForeground(new java.awt.Color(0, 0, 0));
        btnLogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOut1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnLogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 240, 80));

        btnUserSecurity.setBackground(new java.awt.Color(255, 255, 255));
        btnUserSecurity.setForeground(new java.awt.Color(0, 0, 0));
        btnUserSecurity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/securityIcon.png"))); // NOI18N
        btnUserSecurity.setText("USER SECURITY");
        btnUserSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSecurityActionPerformed(evt);
            }
        });
        jPanel4.add(btnUserSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 240, 80));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 260, 670));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpensesActionPerformed
        frmExpense obj = new frmExpense();
        obj.setVisible(true);
    }//GEN-LAST:event_btnExpensesActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        frmReports obj = new frmReports();
        obj.setVisible(true);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnUserControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserControlActionPerformed
        frmUserControl obj = new frmUserControl();
        obj.setVisible(true);
    }//GEN-LAST:event_btnUserControlActionPerformed

    private void btnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptActionPerformed
        frmReceiptTable obj = new frmReceiptTable();
        obj.setVisible(true);
    }//GEN-LAST:event_btnReceiptActionPerformed

    private void btnCashieringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashieringActionPerformed
        frmCashiering obj = new frmCashiering();
        obj.setVisible(true);
    }//GEN-LAST:event_btnCashieringActionPerformed

    private void btnLPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLPOActionPerformed
        frmPurchaseOrder obj = new frmPurchaseOrder();
        obj.setVisible(true);
    }//GEN-LAST:event_btnLPOActionPerformed

    private void btnStockAdjustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockAdjustActionPerformed
        frmStockAdjust obj = new frmStockAdjust();
        obj.setVisible(true);
    }//GEN-LAST:event_btnStockAdjustActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        frmLogin obj = new frmLogin();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        frmProduct obj = new frmProduct();
        obj.setVisible(true);
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        frmSupplierMaster obj = new frmSupplierMaster();
        obj.setVisible(true);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnLogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOut1ActionPerformed

    private void btnUserSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSecurityActionPerformed
        frmUserSecurity obj = new frmUserSecurity();
        obj.setVisible(true);
    }//GEN-LAST:event_btnUserSecurityActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        frmCustomer obj = new frmCustomer();
        obj.setVisible(true);
    }//GEN-LAST:event_btnCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashiering;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnExpenses;
    private javax.swing.JButton btnLPO;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogOut1;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnReceipt;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnStockAdjust;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btnUserControl;
    private javax.swing.JButton btnUserSecurity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
