
package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
public class frmUserSecurity extends javax.swing.JFrame {
dbConnection dbConn = new dbConnection();
String GetCategory,GetAdmin,GetUserId;
String checkProduct,checkSupplier,checkLpo,checkInventory,
        checkSales,checkExpense,checkReceipt,checkReports,checkUserControl,checkUserSecurity;
    public frmUserSecurity() {
        initComponents();
        dbConn.doConnect();
        FillComboUsers();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(frmUserSecurity.DISPOSE_ON_CLOSE);
        
        UncheckAll();
        cmbUserName.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CheckAccess();
            }
        });
       
    }
    
    private void UncheckAll(){
        chkProduct.setSelected(false);
        chkSupplier.setSelected(false);
        chkInventory.setSelected(false);
        chkLpo.setSelected(false);
        chkReports.setSelected(false);
        chkUserControl.setSelected(false);
        chkExpense.setSelected(false);
    }
    public void CheckUserAccessLocal(){
        try{
            dbConn.pstmt = dbConn.conn.prepareStatement("Select * from tblusersecurity where us_name =?");
            dbConn.pstmt.setString(1, cmbUserName.getSelectedItem().toString());
            dbConn.rs = dbConn.pstmt.executeQuery();
            if (dbConn.rs.next()){
                checkExpense = dbConn.rs.getString("us_expense");
                checkInventory = dbConn.rs.getString("us_stockadjust");
                checkLpo= dbConn.rs.getString("us_lpo");
                checkProduct = dbConn.rs.getString("us_product");
                checkReceipt= dbConn.rs.getString("us_receipt");
                
                checkReports= dbConn.rs.getString("us_reports");
                checkSales = dbConn.rs.getString("us_cashier");
                checkSupplier = dbConn.rs.getString("us_supplier");
                checkUserControl = dbConn.rs.getString("us_usercontrol");
                checkUserSecurity = dbConn.rs.getString("us_usersecurity");
            }
            dbConn.pstmt.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void CheckAccess(){
        CheckUserAccessLocal();
        if (checkExpense.equals("Y")){
            chkExpense.setSelected(true);
        }else{
            chkExpense.setSelected(false);
        }
        
        if (checkInventory.equals("Y")){
            chkInventory.setSelected(true);
        }else{
            chkInventory.setSelected(false);
        
        }
        
        if (checkLpo.equals("Y")){
            chkLpo.setSelected(true);
        }else{
            chkLpo.setSelected(false);
        
        }
        
        if (checkProduct.equals("Y")){
            chkProduct.setSelected(true);
        }else{
            chkProduct.setSelected(false);
        
        }
        
        if (checkReceipt.equals("Y")){
            chkReceipt.setSelected(true);
        }else{
            chkReceipt.setSelected(false);
        
        }
        
        if (checkReports.equals("Y")){
            chkReports.setSelected(true);
        }else{
            chkReports.setSelected(false);
        
        }
        
        if (checkSales.equals("Y")){
            chkSales.setSelected(true);
        }else{
            chkSales.setSelected(false);
        }
        
        if (checkSupplier.equals("Y")){
            chkSupplier.setSelected(true);
        }else{
            chkSupplier.setSelected(false);
        
        }
        
        if (checkUserControl.equals("Y")){
            chkUserControl.setSelected(true);
        }else{
            chkUserControl.setSelected(false);
        }
        
        if (checkUserSecurity.equals("Y")){
            chkUserSecurity.setSelected(true);
        }else{
            chkUserSecurity.setSelected(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cmbUserName = new javax.swing.JComboBox<>();
        chkProduct = new javax.swing.JCheckBox();
        chkSupplier = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        chkLpo = new javax.swing.JCheckBox();
        chkInventory = new javax.swing.JCheckBox();
        chkReports = new javax.swing.JCheckBox();
        chkUserSecurity = new javax.swing.JCheckBox();
        chkUserControl = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        chkExpense = new javax.swing.JCheckBox();
        chkReceipt = new javax.swing.JCheckBox();
        chkSales = new javax.swing.JCheckBox();
        chkApplyToAll = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Security");

        jPanel1.setBackground(new java.awt.Color(214, 214, 194));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(214, 214, 194));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbUserName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbUserNameMouseReleased(evt);
            }
        });
        jPanel2.add(cmbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, -1));

        chkProduct.setForeground(new java.awt.Color(0, 0, 0));
        chkProduct.setText("Product");
        chkProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chkProductMouseReleased(evt);
            }
        });
        jPanel2.add(chkProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        chkSupplier.setForeground(new java.awt.Color(0, 0, 0));
        chkSupplier.setText("Supplier");
        chkSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chkSupplierMouseReleased(evt);
            }
        });
        jPanel2.add(chkSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, 10));

        chkLpo.setForeground(new java.awt.Color(0, 0, 0));
        chkLpo.setText("Local Purchase Order");
        chkLpo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chkLpoMouseReleased(evt);
            }
        });
        jPanel2.add(chkLpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        chkInventory.setForeground(new java.awt.Color(0, 0, 0));
        chkInventory.setText("Inventory (Stock Adjust)");
        chkInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chkInventoryMouseReleased(evt);
            }
        });
        jPanel2.add(chkInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        chkReports.setForeground(new java.awt.Color(0, 0, 0));
        chkReports.setText("Reports");
        chkReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chkReportsMouseReleased(evt);
            }
        });
        jPanel2.add(chkReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        chkUserSecurity.setForeground(new java.awt.Color(0, 0, 0));
        chkUserSecurity.setText("User Security");
        jPanel2.add(chkUserSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        chkUserControl.setForeground(new java.awt.Color(0, 0, 0));
        chkUserControl.setText("User Control");
        chkUserControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chkUserControlMouseReleased(evt);
            }
        });
        chkUserControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUserControlActionPerformed(evt);
            }
        });
        jPanel2.add(chkUserControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DefaultImages/SaveIcon.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 80, 70));

        chkExpense.setForeground(new java.awt.Color(0, 0, 0));
        chkExpense.setText("Expense");
        chkExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chkExpenseMouseReleased(evt);
            }
        });
        chkExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkExpenseActionPerformed(evt);
            }
        });
        jPanel2.add(chkExpense, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        chkReceipt.setForeground(new java.awt.Color(0, 0, 0));
        chkReceipt.setText("Receipt Records");
        jPanel2.add(chkReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        chkSales.setForeground(new java.awt.Color(0, 0, 0));
        chkSales.setText("Sales/Cashier");
        chkSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chkSalesMouseReleased(evt);
            }
        });
        jPanel2.add(chkSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        chkApplyToAll.setForeground(new java.awt.Color(0, 0, 0));
        chkApplyToAll.setText("Apply To All");
        chkApplyToAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkApplyToAllMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chkApplyToAllMouseReleased(evt);
            }
        });
        jPanel2.add(chkApplyToAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 360, 370));

        jPanel3.setBackground(new java.awt.Color(214, 214, 194));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 153)));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("User Security");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkUserControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUserControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkUserControlActionPerformed
    private void CheckAdmin(){
        CheckCredentials();
        if (GetAdmin.equals("Y")){
            chkProduct.setSelected(true);
            chkSupplier.setSelected(true);
            chkLpo.setSelected(true);
            chkSales.setSelected(true);
            chkInventory.setSelected(true);
            chkExpense.setSelected(true);
            chkReceipt.setSelected(true);
            chkReports.setSelected(true);
            chkUserControl.setSelected(true);
            chkUserSecurity.setSelected(true);
        }else{
            chkProduct.setSelected(false);
            chkSupplier.setSelected(false);
            chkLpo.setSelected(false);
            chkSales.setSelected(false);
            chkInventory.setSelected(false);
            chkExpense.setSelected(false);
            chkReceipt.setSelected(false);
            chkReports.setSelected(false);
            chkUserControl.setSelected(false);
            chkUserSecurity.setSelected(false);
        
        }
    }
    private void CheckCredentials(){
        try{
            dbConn.pstmt = dbConn.conn.prepareStatement("Select * from tblusercontrol where accountName=?");
            dbConn.pstmt.setString(1, cmbUserName.getSelectedItem().toString());
            dbConn.rs = dbConn.pstmt.executeQuery();
            if (dbConn.rs.next()){
                GetCategory = dbConn.rs.getString("position");
                GetAdmin = dbConn.rs.getString("isAdmin");
                GetUserId = dbConn.rs.getString("userName");
            }
            dbConn.pstmt.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void FillComboUsers(){
        cmbUserName.removeAllItems();
        try{
            dbConn.pstmt = dbConn.conn.prepareStatement("Select * from tblusercontrol order by accountName");
            dbConn.rs =dbConn.pstmt.executeQuery();
            while(dbConn.rs.next()){
                cmbUserName.addItem(dbConn.rs.getString("accountName"));
            }
            dbConn.pstmt.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void chkProductMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkProductMouseReleased
      
    }//GEN-LAST:event_chkProductMouseReleased

    private void chkSupplierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkSupplierMouseReleased
     
    }//GEN-LAST:event_chkSupplierMouseReleased

    private void chkLpoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkLpoMouseReleased
     
    }//GEN-LAST:event_chkLpoMouseReleased

    private void chkInventoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkInventoryMouseReleased
      
    }//GEN-LAST:event_chkInventoryMouseReleased

    private void chkReportsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkReportsMouseReleased
       
    }//GEN-LAST:event_chkReportsMouseReleased

    private void chkUserControlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkUserControlMouseReleased
      
    }//GEN-LAST:event_chkUserControlMouseReleased

    private void cmbUserNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbUserNameMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUserNameMouseReleased
    private void CheckBoxCheck(){
       if (chkExpense.isSelected()){
           checkExpense = "Y";
       }else{
           checkExpense = "N";
       }
       
       if (chkInventory.isSelected()){
           checkInventory = "Y";
       }else{
           checkInventory = "N";
       }
       
       if (chkLpo.isSelected()){
           checkLpo = "Y";
       }else{
           checkLpo = "N";
       }
       
       if (chkProduct.isSelected()){
           checkProduct = "Y";
       }else{
           checkProduct = "N";
       }
       
       if (chkReceipt.isSelected()){
           checkReceipt = "Y";
       }else{
           checkReceipt = "N";
       }
       
       if (chkReports.isSelected()){
           checkReports = "Y";
       }else{
           checkReports = "N";
       }
       
       if (chkSales.isSelected()){
           checkSales = "Y";
       }else{
           checkSales = "N";
       }
       
       if (chkSupplier.isSelected()){
           checkSupplier = "Y";
       }else{
           checkSupplier = "N";
       }
       
       if (chkUserControl.isSelected()){
           checkUserControl = "Y";
       }else{
           checkUserControl = "N";
       }
       
       if (chkUserSecurity.isSelected()){
           checkUserSecurity = "Y";
       }else{
           checkUserSecurity = "N";
       }
        
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            CheckBoxCheck();
            try{
                String SQLQuery = "update tblusersecurity set us_product=?,us_supplier=?,us_lpo=?,us_stockadjust=?,us_cashier=?,"
                        + "us_expense=?,us_receipt=?,us_reports=?,us_usercontrol=?,us_usersecurity=?,"
                        + "us_adduser=?,us_date=? where us_name=?";
                dbConn.pstmt = dbConn.conn.prepareStatement(SQLQuery);
                dbConn.pstmt.setString(1, checkProduct);
                dbConn.pstmt.setString(2, checkSupplier);
                dbConn.pstmt.setString(3, checkLpo);
                dbConn.pstmt.setString(4, checkInventory);
                dbConn.pstmt.setString(5, checkSales);
                dbConn.pstmt.setString(6, checkExpense);
                dbConn.pstmt.setString(7, checkReceipt);
                dbConn.pstmt.setString(8, checkReports);
                dbConn.pstmt.setString(9, checkUserControl);
                dbConn.pstmt.setString(10, checkUserSecurity);
                dbConn.pstmt.setString(11,dbConn.LoggedInUser );
                dbConn.pstmt.setString(12, dbConn.sdfDateGlobal.format(dbConn.todayDateGlobal));
                dbConn.pstmt.setString(13, cmbUserName.getSelectedItem().toString());
                dbConn.saveAuditTrail("UPDATED USER ACCESS: " + cmbUserName.getSelectedItem().toString());
                dbConn.pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Acccess Level Saved");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void chkExpenseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkExpenseMouseReleased
     
    }//GEN-LAST:event_chkExpenseMouseReleased

    private void chkExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkExpenseActionPerformed

    private void chkSalesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkSalesMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSalesMouseReleased

    private void chkApplyToAllMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkApplyToAllMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_chkApplyToAllMouseReleased

    private void chkApplyToAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkApplyToAllMouseClicked
        if (chkApplyToAll.isSelected()){
            chkExpense.setSelected(true);
            chkInventory.setSelected(true);
            chkLpo.setSelected(true);
            chkProduct.setSelected(true);
            chkReceipt.setSelected(true);
            chkReports.setSelected(true);
            chkSales.setSelected(true);
            chkSupplier.setSelected(true);
            chkUserControl.setSelected(true);
            chkUserSecurity.setSelected(true);
        }else{
            chkExpense.setSelected(false);
            chkInventory.setSelected(false);
            chkLpo.setSelected(false);
            chkProduct.setSelected(false);
            chkReceipt.setSelected(false);
            chkReports.setSelected(false);
            chkSales.setSelected(false);
            chkSupplier.setSelected(false);
            chkUserControl.setSelected(false);
            chkUserSecurity.setSelected(false);
        }
    }//GEN-LAST:event_chkApplyToAllMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUserSecurity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkApplyToAll;
    private javax.swing.JCheckBox chkExpense;
    private javax.swing.JCheckBox chkInventory;
    private javax.swing.JCheckBox chkLpo;
    private javax.swing.JCheckBox chkProduct;
    private javax.swing.JCheckBox chkReceipt;
    private javax.swing.JCheckBox chkReports;
    private javax.swing.JCheckBox chkSales;
    private javax.swing.JCheckBox chkSupplier;
    private javax.swing.JCheckBox chkUserControl;
    private javax.swing.JCheckBox chkUserSecurity;
    private javax.swing.JComboBox<String> cmbUserName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
